### ISSUE TITLE
Call to a member function getTheme() on null

### ISSUE THREAD

**Issue by G2PCraft** [DarkSystem-PE/DarkSystem#97]
```
Fatal error: Uncaught Error: Call to a member function getTheme() on null in C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php:264
Stack trace:
#0 C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php(82): pocketmine\utils\MainLogger->send('**** FAILED TO ...', 'critical', 'CRITICAL', '\xC2\xA7c')
#1 C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\network\raknet\server\UDPServerSocket.php(27): pocketmine\utils\MainLogger->critical('**** FAILED TO ...', true, true, 0)
#2 C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\network\raknet\server\RakNetServer.php(231): pocketmine\network\raknet\server\UDPServerSocket->__construct(Object(pocketmine\utils\MainLogger), 19132, '0.0.0.0')
#3 [internal function]: pocketmine\network\raknet\server\RakNetServer->run()
#4 {main}
  thrown in C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php on line 264

Fatal error: Uncaught Error: Call to a member function getTheme() on null in C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php:264
Stack trace:
#0 C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php(66): pocketmine\utils\MainLogger->send('RakNet crashed!', 'emergency', 'EMERGENCY', '\xC2\xA7c')
#1 C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\network\raknet\server\RakNetServer.php(137): pocketmine\utils\MainLogger->emergency('RakNet crashed!')
#2 [internal function]: pocketmine\network\raknet\server\RakNetServer->shutdownHandler()
#3 {main}
  thrown in C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\utils\MainLogger.php on line 264

Notice: Uninitialized string offset: 1098 in C:\Users\Administrator\Desktop\LobbyMainnnnnsnnsssss\src\pocketmine\nbt\NBT.php on line 419
```

**Comment by G2PCraft** [comment]
When run DS server in same port that i already run

**Comment by DarkYusuf13** [comment]
Write "theme: classic" into server.properties
